import React from "react";
import Layout from '../components/layout';
import Head from "../components/head"
import ReactDataGrid from 'react-data-grid';
import { Link } from "gatsby"

const LinkFormatter = ({ value }) => {
    const link = value.split(',')
    return <a href={link[1]}>{link[0]}</a>
};

const columns = [
  { key: 'date', name: 'Date (YYYY/MM/DD)' },
  { key: 'link', name: 'Link', formatter: LinkFormatter },
  { key: 'tags', name: 'Tags' } ];

const rows = [
{date: '2019/02/27', link: 'Immersive linear algebra,http://immersivemath.com/ila/index.html', tags: 'Math'},
{date: '2019/02/27', link: 'Professional Software Development, by Mike G.Miller. Chapter 5 - Software Quality,https://mixmastamyk.bitbucket.io/pro_soft_dev/sdlc_5_qa.html', tags: 'Testing'},
{date: '2019/02/26', link: 'Test Automation University,https://testautomationu.applitools.com/', tags: 'Testing'},
{date: '2019/02/20', link: 'Philosophy Now,https://philosophynow.org/', tags: 'Learning'},
{date: '2019/02/20', link: 'Free HTML Website templates,https://htmltemplates.co/', tags: 'Web'},
{date: '2019/02/20', link: 'Y Combinator Resources for Developers,https://ycombinator.dev/', tags: 'Dev, Tools'},
{date: '2019/02/20', link: 'Software Unit Test Smells,https://testsmells.github.io/', tags: 'Testing'},
{date: '2019/02/20', link: 'xUnit Patterns Test Smells,http://xunitpatterns.com/Test%20Smells.html', tags: 'Testing'},
{date: '2019/02/12', link: 'Automation Panda,https://automationpanda.com/', tags: 'Testing'},
{date: '2019/02/06', link: 'Selenium SonarLint,https://www.sonarlint.org/', tags: 'Testing'},
{date: '2019/01/25', link: 'Modern Testing Principles, AB Testing Podcast,https://www.angryweasel.com/ABTesting/modern-testing-principles/', tags: 'Podcast, Testing'},
{date: '2019/01/25', link: 'Association for Software Testing (AST),https://www.associationforsoftwaretesting.org/', tags: 'Testing'},
{date: '2019/01/25', link: 'Programming Fonts,https://app.programmingfonts.org', tags: 'Development'},
{date: '2019/01/16', link: 'Testing is Believing - Ash Winter,http://testingisbelieving.blogspot.com/', tags: 'Testing'},
{date: '2019/01/12', link: 'Tricentis,https://www.tricentis.com/', tags: 'Testing'},
{date: '2019/01/12', link: 'Good Reads,https://www.goodreads.com/', tags: 'Learning'},
{date: '2019/01/12', link: 'Software Tester - Huib Schoots,http://www.huibschoots.nl/', tags: 'Testing'},
{date: '2019/01/12', link: 'All Things Testing - Toyer Mamoojee,https://toyerm.wordpress.com/', tags: 'Testing'},
{date: '2019/01/12', link: 'Mabl - Advancing QA using ML,https://www.mabl.com/', tags: 'Testing'},
{date: '2019/01/12', link: 'Quality Remarks - Keith Klain,http://qualityremarks.com/', tags: 'Testing'},
{date: '2019/01/12', link: 'Exercism - Code practice and mentorship,https://exercism.io/', tags: 'Development'},
{date: '2019/01/10', link: 'Test Automation University,https://testautomationu.applitools.com/', tags: 'Testing'},
{date: '2019/01/10', link: 'Testing Conferences,https://testingconferences.org/', tags: 'Testing, Monthly'},
{date: '2019/01/10', link: 'The Business of Testing,https://www.thebusinessoftesting.com/', tags: 'Testing, Podcast'},
{date: '2019/01/10', link: 'Code Magazine,https://www.codemag.com', tags: 'Development, Monthly'},
{date: '2019/01/07', link: 'Stories from a Software Tester,http://testerstories.com/', tags: 'Testing'},
{date: '2018/12/30', link: 'The happy secret to better work by Shawn Achor,https://www.youtube.com/watch?v=fLJsdqxnZb0&feature=youtu.be', tags: 'Life'},
{date: '2018/12/19', link: 'Grow Your Technical Skills with Google,https://techdevguide.withgoogle.com/', tags: 'Development'},
{date: '2018/12/19', link: 'Kaplan IT Training,https://www.kaplanittraining.com/', tags: 'Development'},
{date: '2018/12/19', link: 'MIT Deep Learning,https://deeplearning.mit.edu/', tags: 'ML'},
{date: '2018/12/02', link: 'Lynq: long range tracker,https://lynqme.com/', tags: 'Tools'},
{date: '2018/12/02', link: 'Beyond Passwords: 2FA, U2F,https://www.troyhunt.com/beyond-passwords-2fa-u2f-and-google-advanced-protection/', tags: 'Tools'},
{date: '2018/11/27', link: 'Machine Learning with AWS,https://aws.amazon.com/training/learning-paths/machine-learning/', tags: 'ML'},
{date: '2018/11/14', link: 'My CSRIC Commercial,https://www.youtube.com/watch?v=hX2kS3fs_Gk', tags: 'Fun'},
{date: '2018/11/14', link: 'Class Central - Search Engine for Online Classes,https://www.class-central.com/', tags: 'Life'},
{date: '2018/11/14', link: 'It\'s Not What You Know, It\'s How You Think,https://medium.com/s/story/the-trick-to-thinking-clearer-and-better-4a61c54114fa', tags: 'Life'},
{date: '2018/11/14', link: 'QualiTest Blog,https://www.qualitestgroup.com/blog/', tags: 'Testing'},
{date: '2018/09/03', link: 'Java JDK,http://jdk.java.net/', tags: 'Java'},
{date: '2018/08/05', link: 'Cognitive Dissonance in Programming,http://hangaroundtheweb.com/2018/07/cognitive-dissonance-in-programming/', tags: 'Testing'},
{date: '2018/07/27', link: 'Thinking Machine Chess,http://www.bewitched.com/chess/', tags: 'Fun'},
{date: '2018/07/16', link: 'How should we evaluate progress in AI?,https://meaningness.com/metablog/artificial-intelligence-progress', tags: 'ML'},
{date: '2018/06/27', link: 'Ways to think about machine learning,https://www.ben-evans.com/benedictevans/2018/06/22/ways-to-think-about-machine-learning-8nefy', tags: 'ML'},
{date: '2018/06/27', link: 'METS - Minimal Essential Testing Strategy,https://www.metstesting.com/', tags: 'Testing'},
{date: '2018/06/16', link: 'Friendly Machine Learning for the Web,https://ml5js.org/', tags: 'ML'},
{date: '2018/06/11', link: 'Reinforcement Learning from scratch,https://blog.insightdatascience.com/reinforcement-learning-from-scratch-819b65f074d8', tags: 'ML'},
{date: '2018/06/11', link: 'AI at Google: our principles,https://blog.google/topics/ai/ai-principles/', tags: 'ML'},
{date: '2018/06/04', link: 'Fiverr,https://www.fiverr.com', tags: 'Work'},
{date: '2018/06/04', link: '39 Machine Learning Resources,https://medium.com/@karamanbk/39-machine-learning-resources-that-will-help-you-in-every-essential-step-b2696515ed9', tags: 'ML'},
{date: '2018/06/04', link: 'A Course in Machine Learning by Hal Daumé III,http://ciml.info/', tags: 'ML'},
{date: '2018/05/23', link: 'Facebook Field Guide to Machine Learning,https://research.fb.com/the-facebook-field-guide-to-machine-learning-video-series/', tags: 'ML'},
{date: '2018/05/23', link: 'Machine Learning Crash Course,https://developers.google.com/machine-learning/crash-course/', tags: 'ML'},
{date: '2018/05/21', link: 'Machine Learning is Fun,https://medium.com/@ageitgey/machine-learning-is-fun-80ea3ec3c471', tags: 'ML'},
{date: '2018/05/21', link: 'Lessons from My First Two Years of AI Research,http://web.mit.edu/tslvr/www/lessons_two_years.html', tags: 'ML'},
{date: '2018/05/21', link: 'Microsoft AI,https://www.microsoft.com/en-us/ai/', tags: 'ML'},
{date: '2018/05/21', link: 'AI School,https://aischool.microsoft.com/learning-paths', tags: 'ML'},
{date: '2018/05/21', link: 'Jabrils Machine Learning YouTube Channel,https://www.youtube.com/channel/UCQALLeQPoZdZC4JNUboVEUg/videos', tags: 'ML'},
{date: '2018/05/21', link: 'Selenium with Python,https://selenium-python.readthedocs.io/', tags: 'Testing'},
{date: '2018/05/21', link: 'Understanding Machine Learning: From Theory to Algorithms,http://www.cs.huji.ac.il/~shais/UnderstandingMachineLearning/', tags: 'ML'},
{date: '2018/05/21', link: 'Michelle Fullwood A gentle introduction to deep learning with TensorFlow PyCon 2017,https://www.youtube.com/watch?v=5e0TbyCkbCY', tags: 'ML'},
{date: '2018/05/21', link: 'Eder Santanas Deep Learning with Python,https://www.amazon.com/Eder-Santanas-Deep-Learning-Python-ebook/dp/B072JB7GQP', tags: 'ML'},
{date: '2018/05/21', link: 'Applied Machine Learning with Python,https://www.amazon.com/Applied-Machine-Learning-Hamidreza-Sattari-ebook/dp/B072JWG361', tags: 'ML'},
{date: '2018/05/21', link: 'CS 189 at UC Berkeley: Introduction to Machine Learning,http://www.eecs189.org/', tags: 'ML'},
{date: '2018/05/21', link: 'A Machine Learning Guide for Average Humans,https://moz.com/blog/learning-machine-learning', tags: 'ML'},
{date: '2018/05/21', link: 'Microsoft AI overview for developers,https://azure.microsoft.com/en-us/resources/videos/build-2018-microsoft-ai-overview-for-developers/', tags: 'Tools'},
{date: '2018/05/21', link: 'Slack,https://slack.com', tags: 'Tools'},
{date: '2018/05/21', link: 'Slack Themes,https://slackthemes.net', tags: 'Tools'},
{date: '2018/05/21', link: 'Elements of AI,https://www.elementsofai.com/', tags: 'ML'},
{date: '2018/05/21', link: 'The Nengo neural simulator,https://www.nengo.ai/', tags: 'ML'},
{date: '2018/05/21', link: 'The 5 Tribes of the ML world,https://medium.com/42ai/the-5-tribes-of-the-ml-world-670ebce96b4c', tags: 'ML'},
{date: '2018/05/21', link: 'Rules of Machine Learning: Best Practices for ML Engineering,https://developers.google.com/machine-learning/rules-of-ml/', tags: 'ML'},
{date: '2018/05/21', link: 'The 5 Tribes of the ML world,https://medium.com/42ai/the-5-tribes-of-the-ml-world-670ebce96b4c', tags: 'ML'},
{date: '2018/05/21', link: 'Data Skeptic Podcast,https://dataskeptic.com/', tags: 'ML'},
{date: '2018/04/16', link: 'Software Engineering Daily,https://softwareengineeringdaily.com/', tags: 'Podcast'},
{date: '2018/04/16', link: 'Rainforest QA,https://www.rainforestqa.com/', tags: 'ML'},
{date: '2018/04/16', link: 'Learning Machines 101: A Gentle Introduction to Artificial Intelligence and Machine Learning,https://www.learningmachines101.com/', tags: 'ML'},
{date: '2018/04/16', link: 'An interview with Russell Smith of Rainforest QA,https://www.softwaredaily.com/post/5a0eb57b2e7b9f000485d41d/Training-the-Machines-with-Russell-Smith', tags: 'QA'},
{date: '2018/04/16', link: 'Kaggle Lego Database,https://www.kaggle.com/rtatman/lego-database', tags: 'Database'},
{date: '2018/04/16', link: 'Online Artificial Intelligence Courses - Microsoft Professional Program,https://academy.microsoft.com/en-us/professional-program/tracks/artificial-intelligence/', tags: 'ML'},
{date: '2018/04/16', link: 'Gitcoin,https://gitcoin.co/', tags: 'Github'},
{date: '2018/04/16', link: 'Comet.ml - Supercharging Machine Learning,https://www.comet.ml/', tags: 'ML'},
{date: '2018/04/16', link: 'Semantris AI Word Game,https://research.google.com/semantris', tags: 'Fun'},
{date: '2018/03/12', link: 'James Jeffers,https://jamesjeffersconsulting.com/', tags: 'Testing'},
{date: '2018/02/25', link: 'Beaufort Fairmont Test Automation,https://beaufortfairmont.com/', tags: 'Testing'},
{date: '2018/02/25', link: 'Shotcut Video Editor,https://www.shotcutapp.com/', tags: 'Tools'},
{date: '2018/02/25', link: 'FastAI,https://www.fast.ai/', tags: 'AI'},
{date: '2018/02/25', link: 'Regexper,https://regexper.com/', tags: 'Regex '},
{date: '2018/02/25', link: 'The Open Sourcerers Magic Spell Book,https://www.javascriptjanuary.com/blog/the-open-sourcerers-magic-spell-book', tags: 'Github, Dev'},
{date: '2018/02/25', link: 'How to Study,https://www.cse.buffalo.edu//~rapaport/howtostudy.html', tags: 'Learning'},
{date: '2018/02/25', link: 'Laws of UX,https://lawsofux.com/', tags: 'Web, Design'},
{date: '2018/02/25', link: 'Programming Notes for Professionals books,https://books.goalkicker.com/', tags: 'Books'},
{date: '2018/02/25', link: 'Choosing a Free HTML Editor to Build Your Website,https://sitebeginner.com/build/freehtmleditor/', tags: 'Web'},
{date: '2018/01/20', link: 'Netlify,https://www.netlify.com/', tags: 'Hosting'},
{date: '2017/12/20', link: 'Pentester lab,https://pentesterlab.com/', tags: 'Testing'},
{date: '2017/12/20', link: 'Cybrary,https://www.cybrary.it/', tags: 'Documentation'},
{date: '2017/12/20', link: 'What nobody tells you about documentation,https://www.divio.com/blog/documentation/', tags: 'Documentation'},
{date: '2017/12/20', link: 'Cross browser testing,https://developer.mozilla.org/en-US/docs/Learn/Tools_and_testing/Cross_browser_testing', tags: 'Testing'},
{date: '2017/12/20', link: 'Joe Colantonio,https://www.joecolantonio.com/', tags: 'Testing'},
{date: '2017/12/20', link: 'Abode QA,http://www.abodeqa.com/', tags: 'Testing'},
{date: '2017/12/20', link: 'Software Testing Class,http://www.softwaretestingclass.com/', tags: 'Testing'},
{date: '2017/12/20', link: 'Sticky Minds,https://www.stickyminds.com/', tags: 'Testing'},
{date: '2017/12/20', link: 'Software Testing Help,https://www.softwaretestinghelp.com/', tags: 'Testing'},
{date: '2017/12/20', link: 'Guru 99,https://www.guru99.com/', tags: 'Testing'},
{date: '2017/12/20', link: 'Katalon Studio,https://www.katalon.com/', tags: 'Testing,Tools'},
{date: '2017/10/05', link: 'Skype Interview,https://interviews.skype.com/en/Quick/', tags: 'Jobs'},
{date: '2017/10/05', link: 'Earth Wind Map,https://earth.nullschool.net/', tags: 'Fun'},
{date: '2017/10/05', link: 'Identity Theft, Credit Reports, and You,https://www.kalzumeus.com/2017/09/09/identity-theft-credit-reports/', tags: 'Life'},
{date: '2017/08/31', link: 'Principles of Chaos Engineering,https://principlesofchaos.org/', tags: 'Testing'},
{date: '2017/08/26', link: 'Beta Family Testers,https://betafamily.com/', tags: 'Testing'},
{date: '2017/08/26', link: 'Free Code Camp,https://www.freecodecamp.org/', tags: 'Web'},
{date: '2017/05/26', link: '99 Tests,https://99tests.com/', tags: 'Testing'},
{date: '2017/03/28', link: 'Bad SSL,https://badssl.com/', tags: 'Web, Tools, Testing'},
{date: '2017/03/28', link: 'To WWW or not WWW,https://www.netlify.com/blog/2017/02/28/to-www-or-not-www/', tags: 'Web'},
{date: '2017/03/28', link: 'What are some things you wish you knew when you started programming?,https://www.quora.com/What-are-some-things-you-wish-you-knew-when-you-started-programming/answer/Ken-Mazaika?share=1', tags: 'Development'},
{date: '2017/03/28', link: 'U.S. Web Design Standards,https://standards.usa.gov/', tags: 'Web, Design'},
{date: '2017/03/28', link: 'Open Source Guides,https://opensource.guide/', tags: 'Development'},
{date: '2017/03/28', link: 'Seeing Theory - Probability and Statistics,https://students.brown.edu/seeing-theory/', tags: 'Math'},
{date: '2017/03/28', link: 'InvestorPlace Dividends,https://investorplace.com/category/stock-picks/dividend', tags: 'Investing'},
{date: '2017/03/28', link: 'Grad Money,https://www.gradmoney.org', tags: 'Investing'},
{date: '2017/03/28', link: 'DiviData,https://www.dividata.com', tags: 'Investing'},
{date: '2017/03/28', link: 'Dividend Channel,https://www.dividendchannel.com', tags: 'Investing'},
{date: '2017/03/28', link: 'The Motley Fool,https://www.fool.com', tags: 'Investing'},
{date: '2017/02/05', link: 'Color Hunt,https://colorhunt.co/', tags: 'Design'},
{date: '2017/02/05', link: 'Timer Tab,http://www.timer-tab.com/', tags: 'Tools'},
{date: '2017/02/05', link: 'Goals vs. Systems,https://blog.dilbert.com/2013/11/18/goals-vs-systems/', tags: 'Life'},
{date: '2017/02/05', link: 'Online Typing Practice for Programmers,http://www.speedcoder.net/', tags: 'Tools'},
{date: '2016/11/30', link: 'JS Foundation,https://js.foundation/', tags: 'JavaScript'},
{date: '2016/11/30', link: 'Regex 101,https://regex101.com/', tags: 'Regex'},
{date: '2016/11/30', link: 'The Bug Count Also Rises,http://www.workpump.com/bugcount/bugcount.html', tags: 'Fun, Testing'},
{date: '2016/11/30', link: 'Dramatically Reducing Software Vulnerabilities,https://csrc.nist.gov/publications/drafts/nistir-8151/nistir8151_draft.pdf', tags: 'Development, Testing'},
{date: '2016/11/30', link: 'Intern; Software testing for humans,https://theintern.io/', tags: 'Node, Testing'},
{date: '2016/11/30', link: 'Error Handling in Node.js,https://www.joyent.com/node-js/production/design/errors', tags: 'Node'},
{date: '2016/11/30', link: 'How to contribute to an open source project on GitHub,https://blog.davidecoppola.com/2016/11/howto-contribute-to-open-source-project-on-github/', tags: 'Github'},
{date: '2016/11/30', link: 'Material Design,https://material.io/', tags: 'Design'},
{date: '2016/11/30', link: 'International Software Testing Qualifications Board,https://www.istqb.org', tags: 'Testing'},
{date: '2016/11/30', link: 'Less Wrong,https://lesswrong.com/', tags: 'Learning'},
{date: '2016/10/01', link: 'Transcendental Granola,https://www.youtube.com/watch?v=fV-E6NoK2L8', tags: 'Fun'},
{date: '2016/10/01', link: 'JavaScript Enlightenment,http://javascriptenlightenment.com/', tags: 'JavaScript, Book'},
{date: '2016/10/01', link: 'Best free Node.js Tutorials,https://www.vandelaydesign.com/best-free-nodejs-tutorials/', tags: 'JavaScript, Node'},
{date: '2016/08/28', link: 'Monaco editor,https://microsoft.github.io/monaco-editor/', tags: 'Web'},
{date: '2016/08/28', link: 'Heroku hosting,https://www.heroku.com/', tags: 'Web'},
{date: '2016/08/28', link: 'ADEPT method to learn new things,https://betterexplained.com/articles/adept-method/', tags: 'Learning'},
{date: '2016/05/23', link: 'SourceTree,https://www.sourcetreeapp.com/', tags: 'Git, Tools'},
{date: '2016/05/23', link: 'Golden Rules for Making Money in 1880,https://www.fourmilab.ch/etexts/www/barnum/moneygetting/', tags: 'Fun'},
{date: '2016/05/23', link: 'OverAPI,http://overapi.com/', tags: 'Programming'},
{date: '2016/05/23', link: 'GitKracken,https://www.gitkraken.com/', tags: 'Git, Tools'},
{date: '2016/03/19', link: 'Sauce Labs automated browser testing,https://saucelabs.com/', tags: 'Tools,Testing'},
{date: '2016/03/19', link: 'The Art of Unix Programming,http://www.catb.org/esr/writings/taoup/html/', tags: 'Programming'},
{date: '2016/03/19', link: 'Say yes to using WWW,https://www.yes-www.org/why-use-www/', tags: 'Web'},
{date: '2016/03/19', link: 'GitHub Code Review Tools,https://github.com/blog/2123-more-code-review-tools', tags: 'Tools,GitHub'},
{date: '2015/12/02', link: 'Making LastPass more secure,https://www.martinvigo.com/even-the-lastpass-will-be-stolen-deal-with-it/', tags: 'Tools,Security'},
{date: '2015/12/02', link: 'Major-General Sir Herbert Stewart,https://en.wikipedia.org/wiki/Herbert_Stewart', tags: 'Fun'},
{date: '2015/12/02', link: 'Office Code Pro Font,https://github.com/nathco/office-code-pro', tags: 'Font'},
{date: '2015/12/02', link: 'GitHub Desktop,https://desktop.github.com/', tags: 'Tools'},
{date: '2015/09/01', link: 'Visual Studio Code,https://code.visualstudio.com', tags: 'Tools'},
{date: '2015/03/19', link: 'How SQLite Is Tested,https://www.sqlite.org/testing.html', tags: 'Testing'},
{date: '2015/03/19', link: 'Bug finding is slow in spite of many eyeballs,https://daniel.haxx.se/blog/2015/02/23/bug-finding-is-slow-in-spite-of-many-eyeballs/', tags: 'Testing'},
{date: '2015/03/19', link: 'Authentication Cheat Sheet,https://www.owasp.org/index.php/Authentication_Cheat_Sheet', tags: 'Security,Web'},
{date: '2015/03/19', link: 'Things I Wish Someone Had Told Me When I Was Learning How to Code,https://medium.freecodecamp.org/things-i-wish-someone-had-told-me-when-i-was-learning-how-to-code-565fc9dcb329', tags: 'Development'},
{date: '2015/03/09', link: 'Three years of Practical Software Engineering at Lifelock,http://camriley.com/lifelock/', tags: 'Testing,Development'},
{date: '2014/08/07', link: 'How to create a file with a . dot prefix in Windows Explorer,https://www.hanselman.com/blog/HowToCreateAFileWithADotPrefixInWindowsExplorer.aspx', tags: 'Tools'},
{date: '2014/08/05', link: 'My secret to getting rid of burnout permanently,https://kentnguyen.com/personal/getting-rid-burnouts/', tags: 'Mindfulness'},
{date: '2014/07/23', link: 'Bootstrap Themes,https://www.prepbootstrap.com/', tags: 'CSS'},
{date: '2014/07/22', link: 'The elegant art of not giving a shit,https://www.raptitude.com/2014/07/not-giving-a-shit/', tags: 'Mindfulness'},
{date: '2014/07/15', link: 'QA is Important,http://thecodist.com/article/qa_qa_we_don_39_t_need_no_stinking_qa/', tags: 'Testing'},
{date: '2014/07/16', link: 'CSS Diner,https://flukeout.github.io/', tags: 'CSS'},
{date: '2014/07/15', link: 'IDE Online,https://ideone.com/', tags: 'Development'},
{date: '2014/06/26', link: 'UTest,https://www.utest.com/', tags: 'Testing'},
{date: '2014/06/20', link: 'The Science of Problem Solving,https://rs.io/the-science-of-problem-solving/', tags: 'Development'},
{date: '2014/06/16', link: 'Online Color Challenge,https://www.xrite.com/hue-test', tags: 'Fun'},
{date: '2014/06/16', link: 'American Software Testing Qualifications Board,https://www.astqb.org/', tags: 'Testing'},
{date: '2014/05/28', link: 'Coding principles every engineer should know,https://medium.com/on-coding/b946b48cc946', tags: 'Development'},
{date: '2017/05/21', link: 'Testing Ember.js,https://guides.emberjs.com/v3.0.0/testing/', tags: 'Testing'},
{date: '2014/05/20', link: 'The multiplicative slowdown effect of testing,http://peternixey.com/post/26074087096/the-multiplicative-slowdown-effect-of-testing', tags: 'Testing, Development'},
{date: '2014/05/20', link: 'Single Responsibility Principle,https://8thlight.com/blog/uncle-bob/2014/05/08/SingleReponsibilityPrinciple.html', tags: 'Development'},
{date: '2014/05/15', link: 'Programming Sucks,https://www.stilldrinking.org/programming-sucks', tags: 'Development'},
{date: '2014/05/14', link: 'Testing Katas,https://www.soapui.org/testing-dojo/testing-katas/what-are-testing-katas-.html', tags: 'Testing'},
{date: '2014/04/21', link: 'The Philosophy of Computer Science at Stanford,https://plato.stanford.edu/entries/computer-science/', tags: 'Development'},
{date: '2014/04/16', link: 'vis.js; a dynamic, browser-based visualization library,http://visjs.org/', tags: 'JavaScript'},
{date: '2014/04/11', link: 'The Testers Headache,https://testers-headache.blogspot.com/', tags: 'Testing'},
{date: '2014/04/10', link: 'Conversational patterns in BDD by Liz Keogh, lunivore,https://lizkeogh.com/2011/09/22/conversational-patterns-in-bdd/', tags: 'Testing'},
{date: '2014/04/10', link: 'Integrated Tests Are A Scam,https://blog.thecodewhisperer.com/permalink/integrated-tests-are-a-scam/', tags: 'Testing'},
{date: '2014/04/07', link: 'Progress Button Styles,https://tympanus.net/Development/ProgressButtonStyles/', tags: 'CSS'},
{date: '2014/04/05', link: 'Scott Hanselmans Complete List of Productivity Tips,https://www.hanselman.com/blog/ScottHanselmansCompleteListOfProductivityTips.aspx', tags: 'Development'},
{date: '2014/03/11', link: 'Microservices,https://martinfowler.com/articles/microservices.html', tags: 'Development'},
{date: '2014/02/27', link: 'Atom,https://atom.io/', tags: 'Tools'},
{date: '2014/02/26', link: 'Try Regex—an interactive regex tutorial,http://tryregex.com/', tags: 'RegEx'},
{date: '2014/02/20', link: 'James Bachs Blog,http://www.satisfice.com/blog/', tags: 'Testing'},
{date: '2014/02/19', link: 'Levels of Excellence,https://johncarlosbaez.wordpress.com/2013/09/29/levels-of-excellence/', tags: 'Development'},
{date: '2014/02/18', link: 'Therac-25 - Wikipedia,https://en.wikipedia.org/wiki/Therac-25', tags: 'Testing'},
{date: '2014/02/06', link: 'Exploratory Testing == Fun Productivity,https://experttesters.com/2013/02/07/exploratory-testing-fun-productivity/', tags: 'Testing'},
{date: '2014/02/06', link: 'Equivalence Class Testing,https://experttesters.com/2013/08/16/equivalence-class-testing/', tags: 'Testing'},
{date: '2014/02/06', link: 'www.ministryoftesting.com Ebooks,https://dojo.ministryoftesting.com/lessons/ebooks-for-software-testers', tags: 'Books,Testing'},
{date: '2014/02/06', link: 'Enjoy testing: Free download - Software Testing Books,https://enjoytesting.blogspot.com/2013/10/free-download-software-testing-books.html', tags: 'Books,Testing'},
{date: '2014/02/06', link: 'E.W.Dijkstra Archive: 1985,https://www.cs.utexas.edu/users/EWD/misc/vanVlissingenInterview.html', tags: 'Development'},
{date: '2014/02/05', link: 'Context-Driven-Testing,http://context-driven-testing.com/', tags: 'Testing'},
{date: '2014/02/04', link: 'James Bach lecture on testing,https://www.youtube.com/watch?v=ILkT_HV9DVU', tags: 'Testing,Video'},
{date: '2014/01/31', link: 'Fallacies,http://www.nizkor.org/features/fallacies/', tags: 'Development'},
{date: '2014/01/30', link: 'GitHub Guides,https://guides.github.com/', tags: 'Github'},
{date: '2014/01/28', link: 'Exploratory Testing,http://exploringuncertainty.com/blog/wp-content/uploads/2013/05/ET_Why_we_do_it_CGI_REV1.00.pdf', tags: 'Testing'},
{date: '2014/01/09', link: 'Seven Habits Study Guide,https://en.wikibooks.org/wiki/Seven_Habits_Study_Guide/Quick_overview_of_the_seven_habits', tags: 'Books'},
{date: '2014/01/08', link: 'Agile Test Automation,http://www.satisfice.com/presentations/agileauto.pdf', tags: 'Testing'},
{date: '2014/01/02', link: 'JavaScript Patterns,https://shichuan.github.io/javascript-patterns/', tags: 'JavaScript,jQuery'},
{date: '2013/12/31', link: 'Developsense Blog,http://www.developsense.com/blog/', tags: 'Testing'},
{date: '2013/12/31', link: 'Gerald Weinbergs Secrets of Writing and Consulting,https://secretsofconsulting.blogspot.co.uk/', tags: 'Testing'},
{date: '2013/12/31', link: 'Exploring Uncertainty,http://exploringuncertainty.com/blog/', tags: 'Testing'},
{date: '2013/12/31', link: 'QA Hates You,http://qahatesyou.com/wordpress/', tags: 'Testing'},
{date: '2013/12/31', link: 'Test Side Story,https://testsidestory.com/', tags: 'Testing'},
{date: '2013/12/31', link: 'Michael Hunter the Braidy Tester,http://www.thebraidytester.com/', tags: 'Testing'},
{date: '2013/12/30', link: 'SFDPO - James Bach - Satisfice, Inc.,http://www.satisfice.com/articles/sfdpo.shtml', tags: 'Testing'},
{date: '2013/12/30', link: 'Thoughts from the test eye,http://thetesteye.com/blog/', tags: 'Testing'},
{date: '2013/12/30', link: 'HICCUPPS,http://www.developsense.com/blog/2012/07/few-hiccupps/', tags: 'Testing'},
{date: '2013/12/30', link: 'Hiccupps,https://qahiccupps.blogspot.com/', tags: 'Testing'},
{date: '2013/12/30', link: 'Ministry of Testing,https://www.ministryoftesting.com/', tags: 'Testing'},
{date: '2013/12/30', link: 'James Bach - Satisfice, Inc.,http://www.satisfice.com/', tags: 'Testing'},
{date: '2013/12/30', link: 'Software Quality Assurance and Testing - Stack Exchange,https://sqa.stackexchange.com/', tags: 'Testing'},
{date: '2013/12/27', link: 'Coding Horror: Making Developers Cry Since 1995,https://blog.codinghorror.com/making-developers-cry-since-1995/', tags: 'Testing'},
{date: '2013/12/26', link: 'The Taxonomy of Terrible Programmers,http://www.aaronstannard.com/post/2013/12/19/The-Taxonomy-of-Terrible-Programmers.aspx', tags: 'Development'},
{date: '2013/12/02', link: 'Software Engineering Code of Ethics and Professional Practice,https://www.acm.org/about-acm/code-of-ethics', tags: 'Development'},
{date: '2013/11/20', link: '.NET Fiddle,https://dotnetfiddle.net/', tags: 'CSharp, Tools'},
{date: '2013/11/07', link: '7 Sins of Doomed Teams,https://thehumanfactor.co/7-sins-of-doomed-teams/', tags: 'Development'},
{date: '2013/10/28', link: 'Learn Git Branching,https://learngitbranching.js.org/', tags: 'Git'},
{date: '2013/10/16', link: 'Wabi-sabi - Wikipedia,https://en.wikipedia.org/wiki/Wabi-sabi', tags: 'Design'},
{date: '2013/10/07', link: 'GitHub Glossary,https://help.github.com/articles/github-glossary/', tags: 'Github'},
{date: '2013/10/04', link: 'Programming Fonts,https://s9w.github.io/font_compare/?rp', tags: 'Development,Font'},
{date: '2013/08/12', link: 'Absolute Centering in CSS,https://codepen.io/shshaw/full/gEiDt', tags: 'CSS'},
{date: '2013/08/05', link: 'Git Best Practices,https://sethrobertson.github.io/GitBestPractices/', tags: 'git'},
{date: '2013/07/29', link: 'E.W.Dijkstra Archive: The Humble Programmer,https://www.cs.utexas.edu/users/EWD/transcriptions/EWD03xx/EWD340.html', tags: 'Development'},
{date: '2013/06/25', link: 'Dilbert,https://dilbert.com/', tags: 'Daily'},
{date: '2013/05/20', link: 'The Linux Information Project,http://www.linfo.org/', tags: 'Development, Linux'},
{date: '2013/04/23', link: 'How I Learned to Become a Failure,https://medium.com/lets-make-things-1/f140cda815eb', tags: 'Development'},
{date: '2013/04/23', link: 'Bad code is the first step towards good code,https://medium.com/lets-make-things/dd9798e25874', tags: 'Development,Web'},
{date: '2013/02/13', link: 'Wordle - Beautiful Word Clouds,http://www.wordle.net/', tags: 'fun'},
{date: '2012/12/14', link: 'FileZilla - The free FTP solution,https://filezilla-project.org/', tags: 'Tools'},
{date: '2012/11/07', link: 'Permission to Suck,https://www.kadavy.net/blog/posts/permission-to-suck/', tags: 'Development'},
{date: '2012/11/06', link: 'Unit testing best practices,https://howtodoinjava.com/best-practices/unit-testing-best-practices-junit-reference-guide/', tags: 'Testing'},
{date: '2012/10/23', link: 'Indent style,https://en.wikipedia.org/wiki/Indent_style', tags: 'Development'},
{date: '2012/10/23', link: 'Kill the Zombies in Your Code,https://www.bitnative.com/2012/10/22/kill-the-zombies-in-your-code/', tags: 'Development'},
{date: '2012/10/15', link: 'Adobe Source Code Pro Font,https://github.com/adobe/Source-Code-Pro/downloads', tags: 'Font'},
{date: '2012/10/12', link: 'Programmer Competency Matrix,http://www.starling-software.com/employment/programmer-competency-matrix.html', tags: 'Development'},
{date: '2012/09/28', link: 'The Four Elements of Simple Design,https://blog.jbrains.ca/permalink/the-four-elements-of-simple-design', tags: 'Development'},
{date: '2012/09/28', link: 'Gokhale Method pain-free back, neck, hips, knees, feet...,https://gokhalemethod.com/', tags: 'Health'},
{date: '2012/08/21', link: 'Believe you can change,http://www.aaronsw.com/weblog/dweck', tags: 'Teaching,Development'},
{date: '2012/08/20', link: 'Russell Kirsch - Inventor of the Computer,https://impossiblehq.com/an-unexpected-ass-kicking', tags: 'Development'},
{date: '2012/08/15', link: 'Computer Science Khan Academy,https://www.khanacademy.org/computing/computer-programming', tags: 'Teaching,Development'},
{date: '2012/08/10', link: 'Design Tip: Never Use Black by Ian Storm Taylor,https://ianstormtaylor.com/design-tip-never-use-black', tags: 'Web,CSS'},
{date: '2012/08/02', link: 'Whys Poignant Guide to Ruby,https://poignant.guide/', tags: 'Ruby'},
{date: '2012/08/01', link: 'Kanban at Microsoft,https://blogs.msdn.com/b/eric_brechner/archive/2012/08/01/too-much-of-a-good-thing-enter-kanban.aspx', tags: 'Kanban'},
{date: '2012/07/30', link: 'Troy Hunt: Lessons in website security anti-patterns by Tesco,https://www.troyhunt.com/lessons-in-website-security-anti/', tags: 'Security,Web'},
{date: '2012/07/20', link: 'Wrong,https://blog.8thlight.com/dave-moore/2012/07/16/youre-going-to-be-wrong.html', tags: 'Development'},
{date: '2012/06/21', link: 'RegEx Fiddle,http://refiddle.com/', tags: 'RegEx'},
{date: '2012/06/21', link: 'Programming Like Kent Beck,https://blog.iterate.no/2012/06/20/programming-like-kent-beck/', tags: 'Development'},
{date: '2012/06/19', link: 'Falsehoods programmers believe about time: Noah Sussman: Infinite Undo,https://infiniteundo.com/post/25326999628/falsehoods-programmers-believe-about-time', tags: 'Development'},
{date: '2012/06/05', link: 'Bootstrap,https://getbootstrap.com/', tags: 'Web'},
{date: '2012/06/05', link: 'Font Awesome,https://fontawesome.com/', tags: 'Web,Font'},
{date: '2012/05/15', link: 'Learn to code Codecademy,https://www.codecademy.com/', tags: 'Teaching,Development'},
{date: '2012/04/24', link: 'I have no idea what I\'m doing by Nathan Kontny,https://ninjasandrobots.com/you-need-some-experience', tags: 'Development'},
{date: '2012/04/19', link: 'Stripe payment system,https://stripe.com/', tags: 'Web'},
{date: '2012/03/21', link: 'Your identity is not Your code,https://collectiveidea.com/blog/archives/2012/03/16/your-identity-your-code/', tags: 'Development'},
{date: '2012/01/24', link: 'Nerd Merit Badges - Welcome,https://www.nerdmeritbadges.com/', tags: 'Shopping'},
{date: '2011/12/06', link: 'HTML5 Elements Quiz,http://thehtml5quiz.com/', tags: 'HTML'},
{date: '2011/11/10', link: 'There, I Fixed It - Redneck Repairs,https://failblog.cheezburger.com/thereifixedit', tags: 'Fun'},
{date: '2011/10/17', link: 'Getting Stuck,https://www.jeffwofford.com/?p=838', tags: 'Development'},
{date: '2011/09/26', link: 'Pandora Radio,https://www.pandora.com/', tags: 'Fun'},
{date: '2011/08/25', link: 'The Six Dumbest Ideas in Computer Security,https://www.ranum.com/security/computer_security/editorials/dumb/index.html', tags: 'Security'},
{date: '2011/08/25', link: 'Zen Stories,http://www.101zenstories.com/', tags: 'Teaching'},
{date: '2011/08/23', link: 'Hackety Hack, why the lucky stiff on Vimeo,https://vimeo.com/5047563', tags: 'Video,Development'},
{date: '2011/06/16', link: 'CSS Lint,http://csslint.net/', tags: 'Testing,CSS'},
{date: '2016/08/24', link: 'The Tao Of Programming,https://thinkdiffere.net/the-tao-of-programming-4dbe01178ed4#.njcpjz3pp', tags: 'Development'},
{date: '2011/05/10', link: '20 Things to Remember If You Love a Person with ADD,https://www.lifehack.org/articles/lifestyle/20-things-remember-you-love-person-with-add.html', tags: 'Health'},
{date: '2011/04/12', link: 'UI-Patterns.com,http://ui-patterns.com/', tags: 'Web'},
{date: '2011/04/11', link: 'Github Issues,https://github.com/blog/831-issues-2-0-the-next-generation', tags: 'Github'},
{date: '2011/04/04', link: 'Coding Horror: Quantity Always Trumps Quality,https://blog.codinghorror.com/quantity-always-trumps-quality/', tags: 'Teaching,Development'},
{date: '2011/02/28', link: 'Hacker News,https://news.ycombinator.com/news', tags: 'Daily'},
{date: '2011/02/20', link: 'Code Review - Stack Exchange,https://codereview.stackexchange.com/', tags: 'Development'},
{date: '2011/01/12', link: 'The Transformation Priority Premise - Uncle Bob\'s Blog,https://blog.8thlight.com/uncle-bob/2013/05/27/TheTransformationPriorityPremise.html', tags: 'Testing'},
{date: '2010/12/17', link: 'Last Pass,https://lastpass.com/', tags: 'Tools,Security'},
{date: '2010/12/15', link: 'InfoQ: Integration Tests Are a Scam,https://www.infoq.com/presentations/integration-tests-scam', tags: 'Testing,Video'},
{date: '2010/12/07', link: 'Telerik,https://www.telerik.com/', tags: 'Web'},
{date: '2010/11/24', link: '10,000 Hours To Develop Talent,https://personalexcellence.co/blog/10000-hours/', tags: 'Teaching'},
{date: '2010/11/03', link: 'Lorem Ipsum - All the facts - Lipsum generator,https://www.lipsum.com/', tags: 'Web'},
{date: '2010/10/16', link: 'GitHub,https://github.com/', tags: 'Github'},
{date: '2010/10/16', link: 'GitHub Markdown,https://help.github.com/categories/writing-on-github/', tags: 'Github'},
{date: '2010/10/07', link: 'WinMerge,http://winmerge.org', tags: 'WinMerge,Git'},
{date: '2010/09/30', link: 'The official US time,https://nist.time.gov/', tags: 'Tools'},
{date: '2010/09/22', link: 'What is the Romans Road to salvation?,https://www.gotquestions.org/Romans-road-salvation.html', tags: 'Religion'},
{date: '2010/09/22', link: 'Set The Bozo Bit,http://c2.com/cgi/wiki?SetTheBozoBit', tags: 'Development'},
{date: '2010/08/28', link: 'NOTEPAD++,https://notepad-plus-plus.org/', tags: 'Tools'},
{date: '2010/08/26', link: 'Git - Fast Version Control System,https://git-scm.com/', tags: 'Git'},
{date: '2010/08/23', link: 'Mocks Aren\'t Stubs,https://martinfowler.com/articles/mocksArentStubs.html', tags: 'Testing'},
{date: '2010/08/23', link: 'Adventures in .NET: Creating Your Own IoC Container,https://adventuresdotnet.blogspot.com/2009/09/creating-your-own-ioc-container.html', tags: 'inversion-of-control'},
{date: '2010/08/09', link: 'Limited WIP Society - Home of Kanban for Software Development,https://limitedwipsociety.ning.com', tags: 'Development'},
{date: '2010/08/03', link: 'MVC 1979 by Trygve Reenskaug,https://heim.ifi.uio.no/~trygver/1979/mvc-2/1979-12-MVC.pdf', tags: 'MVC'},
{date: '2010/07/22', link: 'Martin Fowler,https://www.martinfowler.com/', tags: 'Development'},
{date: '2010/07/19', link: 'The New Methodology,https://martinfowler.com/articles/newMethodology.html', tags: 'Development'},
{date: '2010/07/16', link: 'JQuery Core Style Guidelines,https://contribute.jquery.org/style-guide/js/', tags: 'jQuery,javascript'},
{date: '2010/07/07', link: 'ThinkGeek :: Stuff for Smart Masses,https://www.thinkgeek.com/', tags: 'Shopping'},
{date: '2010/07/05', link: 'Index of the HTML 4 Elements,https://www.w3.org/TR/html401/index/elements.html', tags: 'Web,HTML'},
{date: '2010/07/05', link: 'Problem Solving,https://msdn.microsoft.com/en-us/library/bb330921(VS.80).aspx', tags: 'Development,Teaching'},
{date: '2010/07/05', link: 'ArticleS.UncleBob.TheBowlingGameKata,http://butunclebob.com/ArticleS.UncleBob.TheBowlingGameKata', tags: 'Testing'},
{date: '2010/07/05', link: 'Code Smell,http://xp.c2.com/CodeSmell.html', tags: 'Development'},
{date: '2010/07/05', link: 'Mastery by George Leonard,https://www.amazon.com/Mastery-Keys-Success-Long-Term-Fulfillment/dp/0452267560', tags: 'Development,Books'},
{date: '2010/07/05', link: 'Stack Overflow,https://stackoverflow.com/', tags: 'Development'},
{date: '2010/07/05', link: 'secretGeek,http://www.secretgeek.net/', tags: 'Development'},
{date: '2010/07/05', link: 'Scott Hanselman,https://www.hanselman.com/blog/', tags: 'Development'},
{date: '2010/07/05', link: 'MSDN Magazine,https://msdn.microsoft.com/en-us/magazine', tags: 'Development,Magazines'},
{date: '2010/07/05', link: 'css Zen Garden: The Beauty in CSS Design,http://www.csszengarden.com/', tags: 'Web,CSS'},
{date: '2010/07/05', link: 'Coding Horror,https://blog.codinghorror.com/', tags: 'Development'}

 const LinksPage = () => {
    return (
<Layout activemenu="home">
        <Head title="Links"
            description="A list of links that I keep up to date" />
    <div>
    <ReactDataGrid
        columns={columns}
        rowGetter={i => rows[i]}
        rowsCount={3}
        minHeight={150}
        enableCellAutoFocus={false}/>

 </div>
 </Layout>
 )
}

export default LinksPage;